apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 377873366186.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 377873366186.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: "6413e242"
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
